### ISSUE TITLE
Riemann Integration ??

### ISSUE THREAD

**Issue by heraldofsolace** [yoursamlan/mind-map#1]
Pretty sure you studied Riemann Integration sitting next to me. Where is it ??????

**Comment by yoursamlan** [comment]
It is rested in peace in the Complex plane. You can't find it with your Real eye...😅😪

**Comment by heraldofsolace** [comment]
brb gonna call GT

**Comment by yoursamlan** [comment]
Better call 2.5 rather than Puchu
